"""empty message

Revision ID: 63291dd64e39
Revises: d68ccfd31ec9
Create Date: 2022-06-09 20:45:17.577486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63291dd64e39'
down_revision = 'd68ccfd31ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'state')
    op.drop_column('users', 'country')
    op.drop_column('users', 'address')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'zip_code')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('zip_code', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('country', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('state', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
