"""empty message

Revision ID: d68ccfd31ec9
Revises: 6b0feeefa22d
Create Date: 2022-06-09 20:34:27.432628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68ccfd31ec9'
down_revision = '6b0feeefa22d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('address', sa.String(length=150), nullable=False))
    op.add_column('users', sa.Column('city', sa.String(length=150), nullable=False))
    op.add_column('users', sa.Column('state', sa.String(length=150), nullable=False))
    op.add_column('users', sa.Column('zip_code', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('country', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country')
    op.drop_column('users', 'zip_code')
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
